lab_4/app/views/person.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import func
from app import NAME_DATA_BASE, mongo_db

bp = Blueprint("person", __name__, url_prefix="/person")


@bp.route("/<uuid>", methods=["GET", "POST"])
def person(uuid):
    if request.method == "POST":
        func.person.delete_person(uuid)
        return redirect(url_for("person.person_all_desc"))
    person = func.person.serialize_person(uuid)
    pcolumns = func.person.serialize_person_columns()
    tests = func.test.serialize_test_all(uuid)
    tcolumns = func.test.serialize_test_columns()
    return render_template(
        "person/person.html", 
        pcolumns=pcolumns,
        person=person,
        tcolumns=tcolumns,
        tests=tests
    )
    
@bp.route("/<uuid>/edit", methods=["GET", "POST"])
def person_edit(uuid):
    if request.method == "POST":
        func.person.update_person(uuid, request.form)
        return redirect(url_for("person.person", uuid=uuid))
    columns = func.person.serialize_person_columns()
    person = func.person.serialize_person(uuid)
    options = func.person.serialize_person_options()
    return render_template(
        "person/person_edit.html",
        columns=columns,
        person=person,
        options=options,
    )

if NAME_DATA_BASE in ['postgres']:

    @bp.route("/asc", methods=["GET"])
    def person_all_asc():
        pagination = func.person.serialize_person_all_asc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/person_all_asc.html", 
            pagination=pagination,
            columns=columns
        )

    @bp.route("/desc", methods=["GET"])
    def person_all_desc():
        pagination = func.person.serialize_person_all_desc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/person_all_desc.html", 
            pagination=pagination,
            columns=columns
        )
    
if NAME_DATA_BASE in ['mongo']:

    @bp.route("/asc", methods=["GET"])
    def person_all_asc():
        pagination = func.person.serialize_person_all_asc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/mongo_person_all_asc.html", 
            pagination=pagination,
            columns=columns
        )

    @bp.route("/desc", methods=["GET"])
    def person_all_desc():
        pagination = func.person.serialize_person_all_desc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/mongo_person_all_desc.html", 
            pagination=pagination,
            columns=columns
        )

@bp.route("/add", methods=["GET", "POST"])
def person_add():
    if request.method == "POST":
        func.person.create_person(request.form)
        return redirect(url_for("person.person_all_desc"))
    columns = func.person.serialize_person_columns(exclude=["outid"])
    options = func.person.serialize_person_options()
    return render_template(
        "person/person_add.html",
        columns=columns,
        options=options,
    )

lab_4/app/views/query.py
from flask import Blueprint, render_template, request
from app import func

bp = Blueprint("query", __name__, url_prefix="/query")


@bp.route("/", methods=["GET", "POST"])
def query():
    if request.method == "POST":
        query_result = func.test.query(request.form)
        return  render_template(
            "query/query_result.html",
            query_result=query_result   
        )
    options = func.test.serialize_test_options()
    return render_template(
        "query/query.html",
        options=options
    )

lab_4/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>

    <style>
        .yellow-text {
            color: #16700e;
        }
    </style>
</head>

<body>
    <nav class="nav" style="margin: 14px">
        <a class="nav-link yellow-text" href="{{ url_for('person.person_all_desc') }}">Результати ЗНО (спадання)</a>
        <a class="nav-link yellow-text" href="{{ url_for('person.person_all_asc') }}">Результати ЗНО (зростання)</a>
        <a class="nav-link yellow-text" href="{{ url_for('query.query') }}">Створення запиту</a>
        <a class="nav-link yellow-text" href="{{ url_for('person.person_add') }}">Додати людину</a>
        
    </nav>

    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
    </script>
</body>

</html>