lab_4/app/models/person.py
import uuid
from app import db


class Person(db.Model):
    outid = db.Column(db.UUID, primary_key = True, default = uuid.uuid4)
    birth = db.Column(db.Integer)
    sextype_id = db.Column(db.ForeignKey("sex_type.id", ondelete="cascade"))
    regname_id = db.Column(db.ForeignKey("regname.id", ondelete="cascade"))
    areaname = db.Column(db.String)
    tername = db.Column(db.String)
    regtypename = db.Column(db.String)
    tertypename = db.Column(db.String)
    classprofilename = db.Column(db.String)
    classlangname = db.Column(db.String)
    eoname = db.Column(db.String)
    eotypename = db.Column(db.String)
    eoregname = db.Column(db.String)
    eoareaname = db.Column(db.String)
    eotername = db.Column(db.String)
    eoparent = db.Column(db.String)
    tests = db.relationship("Test", cascade="all,delete-orphan", lazy=True, back_populates="person")
    sextype = db.relationship("SexType", lazy=True)
    regname = db.relationship("Regname", lazy=True)
    

lab_4/app/views/person.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import func
from app import NAME_DATA_BASE, mongo_db

bp = Blueprint("person", __name__, url_prefix="/person")


@bp.route("/<uuid>", methods=["GET", "POST"])
def person(uuid):
    if request.method == "POST":
        func.person.delete_person(uuid)
        return redirect(url_for("person.person_all_desc"))
    person = func.person.serialize_person(uuid)
    pcolumns = func.person.serialize_person_columns()
    tests = func.test.serialize_test_all(uuid)
    tcolumns = func.test.serialize_test_columns()
    return render_template(
        "person/person.html", 
        pcolumns=pcolumns,
        person=person,
        tcolumns=tcolumns,
        tests=tests
    )
    
@bp.route("/<uuid>/edit", methods=["GET", "POST"])
def person_edit(uuid):
    if request.method == "POST":
        func.person.update_person(uuid, request.form)
        return redirect(url_for("person.person", uuid=uuid))
    columns = func.person.serialize_person_columns()
    person = func.person.serialize_person(uuid)
    options = func.person.serialize_person_options()
    return render_template(
        "person/person_edit.html",
        columns=columns,
        person=person,
        options=options,
    )

if NAME_DATA_BASE in ['postgres']:

    @bp.route("/asc", methods=["GET"])
    def person_all_asc():
        pagination = func.person.serialize_person_all_asc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/person_all_asc.html", 
            pagination=pagination,
            columns=columns
        )

    @bp.route("/desc", methods=["GET"])
    def person_all_desc():
        pagination = func.person.serialize_person_all_desc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/person_all_desc.html", 
            pagination=pagination,
            columns=columns
        )
    
if NAME_DATA_BASE in ['mongo']:

    @bp.route("/asc", methods=["GET"])
    def person_all_asc():
        pagination = func.person.serialize_person_all_asc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/mongo_person_all_asc.html", 
            pagination=pagination,
            columns=columns
        )

    @bp.route("/desc", methods=["GET"])
    def person_all_desc():
        pagination = func.person.serialize_person_all_desc()
        columns = func.person.serialize_person_columns()
        return render_template(
            "person/mongo_person_all_desc.html", 
            pagination=pagination,
            columns=columns
        )

@bp.route("/add", methods=["GET", "POST"])
def person_add():
    if request.method == "POST":
        func.person.create_person(request.form)
        return redirect(url_for("person.person_all_desc"))
    columns = func.person.serialize_person_columns(exclude=["outid"])
    options = func.person.serialize_person_options()
    return render_template(
        "person/person_add.html",
        columns=columns,
        options=options,
    )

lab_4/app/views/test.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import func

bp = Blueprint("test", __name__, url_prefix="/test")


@bp.route("/<person_uuid>/<id>", methods=["GET", "POST"])
def test(person_uuid, id):
    id = int(id)
    if request.method == "POST":
        func.test.delete_test(id)
        return redirect(url_for("person.person", uuid=person_uuid))
    test = func.test.serialize_test(id)
    columns = func.test.serialize_test_columns()
    return render_template(
        "test/test.html", 
        columns=columns,
        test=test
    )

@bp.route("/add/<person_uuid>", methods=["GET", "POST"])
def test_add(person_uuid):
    if request.method == "POST":
        func.test.create_test(person_uuid, request.form)
        return redirect(url_for("person.person", uuid=person_uuid))
    columns = func.test.serialize_test_columns(exclude=["id"])
    person = func.person.serialize_person(person_uuid)
    options = func.test.serialize_test_options()
    return render_template(
        "test/test_add.html",
        columns=columns,
        person=person,
        options=options,
    )

@bp.route("/edit/<person_uuid>/<id>", methods=["GET", "POST"])
def test_edit(person_uuid, id):
    id = int(id)
    if request.method == "POST":
        func.test.update_test(id, request.form)
        return redirect(url_for("person.person", uuid=person_uuid))
    columns = func.test.serialize_test_columns()
    test = func.test.serialize_test(id)
    options = func.test.serialize_test_options()
    return render_template(
        "test/test_edit.html",
        columns=columns,
        test=test,
        options=options,
    )

lab_4/app/templates/person/mongo_person_all_asc.html
{% extends 'base.html' %}

{% block title %} Persons {% endblock %}

{% block content %}
<!-- <a type="button" class="btn btn-primary" href="{{ url_for('person.person_add') }}">Додати людину</a> -->

<style>
  .yellow-text {
      color: #16700e;
  }

  .yellow-pagination .page-link {
      color: #16700e;
      background-color: #16700e;
      border-color: #16700e;
  }

  .yellow-pagination .page-link:hover,
  .yellow-pagination .page-item.active .page-link {
      background-color: #16700e;
      border-color: #16700e;
  }

  .yellow-column th {
      color: #16700e;
  }
</style>

<img src="MongoDB_Logo.png" alt="MongoDB_Logo Image" width="400" height="300">

<table class="table yellow-column style="margin-top: 50px;">
  <thead>
      <tr>
          {% for column in columns %}
              <th scope="col" class="yellow-column">{{column}}</th>
          {% endfor %}
      </tr>
  </thead>
  <tbody>
      {% for person in pagination %}
          <tr>
              {% for column in columns %}
                  <td class="yellow-column">
                    <a href="{{ url_for('person.person', uuid=person['outid']) }}">
                      {{ person[column] }}
                    </a>
                  </td>
              {% endfor %}
          </tr>
      {% endfor %}
  </tbody>
</table>


{% endblock %}

{% macro render_pagination(pagination, endpoint) %}
  <div class="page-items yellow-text">
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </div>
  <ul class="pagination pagination-sm yellow-pagination">
    {% for page in pagination.iter_pages() %}
      {% if page %}
        <li class="page-item yellow-text {{ 'active' if page == pagination.page else '' }}">
          <a class="page-link yellow-text" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
      {% else %}
        <span class="page-link yellow-text">…</span>
      {% endif %}
    {% endfor %}
  </ul>
{% endmacro %}

lab_4/app/templates/person/mongo_person_all_desc.html
{% extends 'base.html' %}

{% block title %} Persons {% endblock %}

{% block content %}
<!-- <a type="button" class="btn btn-primary" href="{{ url_for('person.person_add') }}">Додати людину</a> -->

<style>
  .yellow-text {
      color: #16700e;
  }

  .yellow-pagination .page-link {
      color: #16700e;
      background-color: #16700e;
      border-color: #16700e;
  }

  .yellow-pagination .page-link:hover,
  .yellow-pagination .page-item.active .page-link {
      background-color: #16700e;
      border-color: #16700e;
  }

  .yellow-column th {
      color: #16700e;
  }
</style>


<img src="MongoDB_Logo.png" alt="MongoDB_Logo Image">
<img src="PostgreSQL_Logo.png" alt="PostgreSQL_Logo Image">


<table class="table yellow-column" style="margin-top: 50px;">
  <thead>
      <tr>
          {% for column in columns %}
              <th scope="col" class="yellow-column">{{column}}</th>
          {% endfor %}
      </tr>
  </thead>
  <tbody>
      {% for person in pagination %}
          <tr>
              {% for column in columns %}
                  <td class="yellow-column">
                    <a href="{{ url_for('person.person', uuid=person['outid']) }}">
                      {{ person[column] }}
                    </a>
                  </td>
              {% endfor %}
          </tr>
      {% endfor %}
  </tbody>
</table>

{% endblock %}

{% macro render_pagination(pagination, endpoint) %}
  <div class="page-items yellow-text">
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </div>
  <ul class="pagination pagination-sm yellow-pagination">
    {% for page in pagination.iter_pages() %}
      {% if page %}
        <li class="page-item yellow-text {{ 'active' if page == pagination.page else '' }}">
          <a class="page-link yellow-text" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
      {% else %}
        <span class="page-link yellow-text">…</span>
      {% endif %}
    {% endfor %}
  </ul>
{% endmacro %}

lab_4/app/templates/person/person.html
{% extends 'base.html' %}

{% block title %} Person {% endblock %}

{% block content %}
<!-- Upper Section -->
<div class="row mt-3">
    <div class="col-md-6">
        {% for column in pcolumns %}
        <div class="form-group">
            <label for={{column}}>{{column}}</label>
            <p class="form-control" id="{{ column }}" name="{{ column }}">{{ person[column] }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-6">
        <form class="btn-group" method="post">
            <a type="button" class="btn btn-primary" href="{{ url_for('person.person_edit', uuid=person['outid']) }}">Редагувати</a>
            <button type="submit" class="btn btn-danger">Видалити</button>
        </form>
    </div>
</div>
<!-- Lower Section -->
<a type="button" class="btn btn-primary" href="{{ url_for('test.test_add', person_uuid=person['outid']) }}">Додати тест</a>
<div class="row mt-3">
    <div class="col">
        <table class="table table-bordered">
            <thead>
                <tr>
                    {% for column in tcolumns %}
                    <th>{{ column }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for test in tests %}
                <tr>
                    {% for column in tcolumns %}
                    <td>
                        <a href="{{ url_for('test.test', id=test['id'], person_uuid=test['outid']) }}">
                        {{ test[column] }}
                        </a>
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

lab_4/app/templates/person/person_add.html
{% extends 'base.html' %}

{% block title %} Person Add {% endblock %}

{% block content %}
<!-- Upper Section -->
<form method="post">
    {% for column in columns %}
    <div class="form-group">
        <label for="{{ column }}">{{ column }}</label>
        {% if column in ("sextype", "regname") %}
        <select id="{{ column }}" name="{{ column }}_id" class="form-select">
            {% for option in options[column] %}
            <option value="{{ option.id }}">{{ option }}</option>
            {% endfor %}
        </select>
        {% else %}
        <input class="form-control" id="{{ column }}" name="{{ column }}">
        {% endif %}
    </div>
    {% endfor %}
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Додати</button>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Назад</button>
    </div>
</form>
{% endblock %}

lab_4/app/templates/person/person_all_asc.html
{% extends 'base.html' %}

{% block title %} Persons {% endblock %}

{% block content %}
<!-- <a type="button" class="btn btn-primary" href="{{ url_for('person.person_add') }}">Додати людину</a> -->

<style>
  .yellow-text {
      color: #0f49b6;
  }

  .yellow-pagination .page-link {
      color: 0f49b6;
      background-color: #0f49b6;
      border-color: #0f49b6;
  }

  .yellow-pagination .page-link:hover,
  .yellow-pagination .page-item.active .page-link {
      background-color: #0f49b6;
      border-color: #0f49b6;
  }

  .yellow-column th {
      color: #0f49b6;
  }
</style>

<img src="PostgreSQL_Logo.png" alt="PostgreSQL_Logo Image" width="400" height="300">

<table class="table yellow-column style="margin-top: 50px;">
  <thead>
      <tr>
          {% for column in columns %}
              <th scope="col" class="yellow-column">{{column}}</th>
          {% endfor %}
      </tr>
  </thead>
  <tbody>
      {% for person in pagination %}
          <tr>
              {% for column in columns %}
                  <td class="yellow-column">
                    <a href="{{ url_for('person.person', uuid=person['outid']) }}">
                      {{ person[column] }}
                    </a>
                  </td>
              {% endfor %}
          </tr>
      {% endfor %}
  </tbody>
</table>


{% endblock %}

{% macro render_pagination(pagination, endpoint) %}
  <div class="page-items yellow-text">
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </div>
  <ul class="pagination pagination-sm yellow-pagination">
    {% for page in pagination.iter_pages() %}
      {% if page %}
        <li class="page-item yellow-text {{ 'active' if page == pagination.page else '' }}">
          <a class="page-link yellow-text" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
      {% else %}
        <span class="page-link yellow-text">…</span>
      {% endif %}
    {% endfor %}
  </ul>
{% endmacro %}

lab_4/app/templates/person/person_all_desc.html
{% extends 'base.html' %}

{% block title %} Persons {% endblock %}

{% block content %}
<!-- <a type="button" class="btn btn-primary" href="{{ url_for('person.person_add') }}">Додати людину</a> -->

<style>
  .yellow-text {
      color: #0f49b6;
  }

  .yellow-pagination .page-link {
      color: #0f49b6;
      background-color: #0f49b6;
      border-color: #0f49b6;
  }

  .yellow-pagination .page-link:hover,
  .yellow-pagination .page-item.active .page-link {
      background-color: #0f49b6;
      border-color: #0f49b6;
  }

  .yellow-column th {
      color: 30f49b6;
  }
</style>

<img src="PostgreSQL_Logo.png" alt="PostgreSQL_Logo Image" width="400" height="300">

<table class="table yellow-column style="margin-top: 50px;">
  <thead>
      <tr>
          {% for column in columns %}
              <th scope="col" class="yellow-column">{{column}}</th>
          {% endfor %}
      </tr>
  </thead>
  <tbody>
      {% for person in pagination %}
          <tr>
              {% for column in columns %}
                  <td class="yellow-column">
                    <a href="{{ url_for('person.person', uuid=person['outid']) }}">
                      {{ person[column] }}
                    </a>
                  </td>
              {% endfor %}
          </tr>
      {% endfor %}
  </tbody>
</table>

{% endblock %}

{% macro render_pagination(pagination, endpoint) %}
  <div class="page-items yellow-text">
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </div>
  <ul class="pagination pagination-sm yellow-pagination">
    {% for page in pagination.iter_pages() %}
      {% if page %}
        <li class="page-item yellow-text {{ 'active' if page == pagination.page else '' }}">
          <a class="page-link yellow-text" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
      {% else %}
        <span class="page-link yellow-text">…</span>
      {% endif %}
    {% endfor %}
  </ul>
{% endmacro %}

lab_4/app/templates/person/person_edit.html
{% extends 'base.html' %}

{% block title %} Person Edit {% endblock %}

{% block content %}
<!-- Upper Section -->
<form method="post">
    {% for column in columns %}
    <div class="form-group">
        <label for="{{ column }}">{{ column }}</label>
        {% if column in ("sextype", "regname") %}
        <select id="{{ column }}" name="{{ column }}_id" class="form-select">
            {% for option in options[column] %}
            <option value="{{ option.id }}" {{ 'selected' if person[column].id == option.id }}>{{ option }}</option>
            {% endfor %}
        </select>
        {% elif column == "outid" %}
        <p id="{{ column }}" name="{{ column }}">{{ person[column] }}</p>
        {% else %}
        <input class="form-control" id="{{ column }}" name="{{ column }}" placeholder="{{ person[column] }}">
        {% endif %}
    </div>
    {% endfor %}
    <div class="btn-group">
        <button type="submit" class="btn btn-primary">Оновити</button>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Назад</button>
    </div>
</form>
{% endblock %}